# Generated by Django 2.1.8 on 2019-05-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190317_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username']},
        ),
    ]
