# Generated by Django 2.1.8 on 2019-05-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='Notification Message')),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Home Message',
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Site Name', max_length=120)),
                ('site_description', models.TextField(default='Website description.')),
                ('canonical_url', models.CharField(default='www.mysite.com', max_length=120)),
                ('publisher', models.CharField(default='Publisher', max_length=120)),
                ('email', models.EmailField(default='my@email.com', max_length=120)),
                ('favicon', models.CharField(default='some url for now', max_length=120)),
                ('site_img', models.CharField(default='some url for now', max_length=120)),
                ('enable_ads', models.BooleanField(default=False)),
                ('enable_analytics', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
