# Generated by Django 2.1.7 on 2019-03-29 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_homemsg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homemsg',
            options={'verbose_name': 'Home Message'},
        ),
    ]
