# Generated by Django 2.1.7 on 2019-03-31 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190329_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homemsg',
            options={},
        ),
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={},
        ),
    ]
