# Generated by Django 2.2 on 2019-04-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_siteconfiguration_enable_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='posts_per_page',
            field=models.IntegerField(default=5),
        ),
    ]
