# Generated by Django 2.2 on 2019-04-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_allow_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='featured',
            new_name='is_featured',
        ),
        migrations.AddField(
            model_name='article',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
