# Generated by Django 2.1.7 on 2019-03-19 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order']},
        ),
    ]
