# Generated by Django 2.2 on 2019-04-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190331_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homemsg',
            options={'verbose_name': 'Home Message'},
        ),
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Site Configuration'},
        ),
    ]
