# Generated by Django 2.2 on 2019-04-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190402_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_ads',
            field=models.BooleanField(default=False),
        ),
    ]
