# Generated by Django 2.2 on 2019-04-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_siteconfiguration_enable_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_analytics',
            field=models.BooleanField(default=False),
        ),
    ]
