# Generated by Django 2.2 on 2019-04-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_siteconfiguration_posts_per_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='posts_per_page',
        ),
    ]
